# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  jobs:
    post_create_environment:
      - pip install poetry

    post_install:
      # Install dependencies using the 'docs' group
      # Note: Set VIRTUAL_ENV manually as a workaround for Poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --no-root --with docs

mkdocs:
  configuration: mkdocs.yml  # Path to your mkdocs.yml file

