site_name: ZephCast Documentation
site_description: Documentation for the ZephCast messaging library
repo_url: https://github.com/zbytealchemy/zephcast
edit_uri: blob/main/docs/

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_if_no_docstring: true
            heading_level: 3

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Configuration: user-guide/configuration.md
    - Examples: user-guide/examples.md
    - Kafka Client: user-guide/kafka.md
    - RabbitMQ Client: user-guide/rabbitmq.md
    - Redis Client: user-guide/redis.md
  - Advanced Topics:
    - Consumer Groups: advanced/consumer-groups.md
    - Error Handling: advanced/error-handling.md
    - Performance: advanced/performance.md
  - API Reference:
    - Kafka API: api/kafka.md
    - RabbitMQ API: api/rabbitmq.md
    - Redis API: api/redis.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
